#!/usr/bin/env python3
# Copyright 2026 the LlamaFactory team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
"""调用 LLM 分析吴卫平模板方 txt 的分类、适应证和加减药规则."""

import argparse
import json
import logging
import re
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any

from medical.config import config


DEFAULT_INPUT_FILE = Path("medical/data/wuweiping_template_prescription.txt")
DEFAULT_OUTPUT_FILE = Path("medical/data/wuweiping_template_prescription_llm_analysis.json")
DEFAULT_MODEL = "doubao-seed-1-6-250615"
logger = logging.getLogger(__name__)


def parse_templates_from_text(text: str) -> list[dict[str, Any]]:
    """Parse txt generated by convert_template_to_txt.py into template records."""
    starts = [match.start() for match in re.finditer(r"^模板ID:\s*", text, flags=re.MULTILINE)]
    templates = []

    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(text)
        block = text[start:end]
        id_match = re.search(r"^模板ID:\s*(\S+)\s*$", block, flags=re.MULTILINE)
        name_match = re.search(r"^方剂名称:\s*(.+?)\s*$", block, flags=re.MULTILINE)
        if not id_match or not name_match:
            continue

        template_id_text = id_match.group(1).strip()
        template_id: int | str = int(template_id_text) if template_id_text.isdigit() else template_id_text
        drugs = []
        for line in block.splitlines():
            drug_match = re.match(
                r"^\s*\d+\.\s+(.+?)\s+([0-9.]+)\s*([^\s(（]+)\s*[\(（](.+?)[\)）]\s*$",
                line,
            )
            if not drug_match:
                continue
            drugs.append(
                {
                    "drug_name": drug_match.group(1).strip(),
                    "quantity": drug_match.group(2).strip(),
                    "unit": drug_match.group(3).strip(),
                    "drug_form": drug_match.group(4).strip(),
                }
            )

        templates.append(
            {
                "template_id": template_id,
                "template_name": name_match.group(1).strip(),
                "drugs": drugs,
                "source_text": block.strip(),
            }
        )

    return templates


def load_templates_from_txt(path: Path) -> list[dict[str, Any]]:
    return parse_templates_from_text(path.read_text(encoding="utf-8"))


def format_template(template: dict[str, Any]) -> str:
    drugs = "、".join(
        f"{drug.get('drug_name', '')}{drug.get('quantity', '')}{drug.get('unit', '')}({drug.get('drug_form', '')})"
        for drug in template.get("drugs", [])
        if drug.get("drug_name")
    )
    return f"模板ID: {template.get('template_id')}\n方剂名称: {template.get('template_name')}\n药物组成: {drugs}"


def chunk_items(items: list[dict[str, Any]], chunk_size: int) -> list[list[dict[str, Any]]]:
    if chunk_size <= 0:
        raise ValueError("chunk_size must be greater than 0")
    return [items[index : index + chunk_size] for index in range(0, len(items), chunk_size)]


def build_batch_prompt(templates: list[dict[str, Any]], batch_index: int, total_batches: int) -> str:
    template_text = "\n\n".join(format_template(template) for template in templates)
    return f"""你是一位经验丰富的中医皮肤科专家，请分析吴卫平医生模板方。

这是第 {batch_index}/{total_batches} 批模板方。请根据方名和药物组成进行“类别级”归纳，不要只逐方罗列。

模板方如下：
{template_text}

请完成：
1. 归纳不同类模板方的适用疾病和适用证候。
2. 归纳每类模板方的治则治法。
3. 识别同类模板的核心药物，说明核心药物依据。
4. 分析加减药规则：什么症状/证候变化对应加哪些药、减哪些药或剂量变化。
5. 输出必须只包含 JSON，不要 Markdown，不要解释性前后缀。

JSON 结构：
{{
  "template_groups": [
    {{
      "category_name": "模板方类别",
      "template_ids": [10480],
      "template_names": ["方名"],
      "applicable_diseases": ["适用疾病"],
      "applicable_syndromes": ["适用证候"],
      "treatment_methods": ["治则治法"],
      "core_drugs": [
        {{"drug_name": "药名", "role": "君/臣/佐/使或核心作用", "reason": "依据"}}
      ],
      "addition_subtraction_rules": [
        {{
          "condition": "症状、体征或证候变化",
          "adjustment": "加药/减药/调整剂量",
          "drugs": ["药名"],
          "reason": "中医依据"
        }}
      ],
      "evidence": "基于方名和药物组成的简要分析依据"
    }}
  ],
  "uncertain_items": [
    {{"template_id": 10480, "reason": "无法明确归类的原因"}}
  ]
}}"""


def build_merge_prompt(batch_analyses: list[dict[str, Any]]) -> str:
    analyses_text = json.dumps(batch_analyses, ensure_ascii=False, indent=2)
    return f"""你是一位经验丰富的中医皮肤科专家。下面是对吴卫平模板方分批分析的结果，请进行汇总合并。

要求：
1. 合并同义或高度相似的模板类别，去重模板 ID、方名、疾病、证候、治则治法。
2. 对同类模板给出最终核心药物，区分核心药和加减药。
3. 整理出可执行的加减药规则，规则应尽量绑定到症状、体征、证候或病机变化。
4. 保留不确定项并说明原因。
5. 输出必须只包含 JSON，不要 Markdown，不要解释性前后缀。

分批分析结果：
{analyses_text}

JSON 结构：
{{
  "template_groups": [
    {{
      "category_name": "模板方类别",
      "template_ids": [10480],
      "template_names": ["方名"],
      "applicable_diseases": ["适用疾病"],
      "applicable_syndromes": ["适用证候"],
      "treatment_methods": ["治则治法"],
      "core_drugs": [
        {{"drug_name": "药名", "role": "核心作用", "reason": "依据"}}
      ],
      "addition_subtraction_rules": [
        {{
          "condition": "症状、体征或证候变化",
          "adjustment": "加药/减药/调整剂量",
          "drugs": ["药名"],
          "reason": "中医依据"
        }}
      ],
      "representative_templates": ["代表方名"],
      "analysis_note": "本类模板方的归纳说明"
    }}
  ],
  "global_addition_subtraction_rules": [
    {{
      "condition": "通用症状、体征或证候变化",
      "adjustment": "加药/减药/调整剂量",
      "drugs": ["药名"],
      "reason": "中医依据"
    }}
  ],
  "uncertain_items": [
    {{"template_id": 10480, "template_name": "方名", "reason": "原因"}}
  ]
}}"""


def extract_json_payload(response_text: str) -> str:
    text = response_text.strip()
    fenced = re.search(r"```(?:json)?\s*(.*?)```", text, flags=re.IGNORECASE | re.DOTALL)
    if fenced:
        text = fenced.group(1).strip()

    starts = [index for index in (text.find("{"), text.find("[")) if index != -1]
    if not starts:
        return text

    decoder = json.JSONDecoder()
    start = min(starts)
    _, end = decoder.raw_decode(text[start:])
    return text[start : start + end]


def parse_llm_json(response_text: str) -> dict[str, Any]:
    payload = extract_json_payload(response_text)
    parsed = json.loads(payload)
    if not isinstance(parsed, dict):
        raise ValueError("LLM response JSON must be an object")
    return parsed


def save_json(data: dict[str, Any], output_file: Path) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def analyze_file(
    input_file: Path,
    output_file: Path,
    llm_call: Callable[[str], str],
    chunk_size: int = 20,
    delay: float = 1.0,
) -> dict[str, Any]:
    templates = load_templates_from_txt(input_file)
    batches = chunk_items(templates, chunk_size)
    batch_analyses = []

    result: dict[str, Any] = {
        "metadata": {
            "input_file": str(input_file),
            "template_count": len(templates),
            "chunk_size": chunk_size,
            "batch_count": len(batches),
        },
        "templates": [
            {
                "template_id": template.get("template_id"),
                "template_name": template.get("template_name"),
                "drugs": template.get("drugs", []),
            }
            for template in templates
        ],
        "batch_analyses": batch_analyses,
        "final_analysis": {},
    }

    for index, batch in enumerate(batches, start=1):
        logger.info(f"Analyzing template batch {index}/{len(batches)}")
        response = llm_call(build_batch_prompt(batch, batch_index=index, total_batches=len(batches)))
        analysis = parse_llm_json(response)
        batch_analyses.append(
            {"batch_index": index, "template_ids": [item["template_id"] for item in batch], "analysis": analysis}
        )
        save_json(result, output_file)
        if delay > 0 and index < len(batches):
            time.sleep(delay)

    logger.info("Merging batch analyses")
    result["final_analysis"] = parse_llm_json(llm_call(build_merge_prompt(batch_analyses)))
    save_json(result, output_file)
    return result


def _config_value(name: str, default: str = "") -> str:
    value = getattr(config, name, default)
    return str(value) if value is not None else default


def create_llm_call(
    model: str | None = None, base_url: str | None = None, api_key: str | None = None
) -> Callable[[str], str]:
    from openai import OpenAI

    provider = _config_value("LLM_PROVIDER", "ark").lower()
    selected_model = model
    selected_base_url = base_url
    selected_api_key = api_key

    if not selected_base_url or not selected_api_key or not selected_model:
        if provider == "dashscope":
            selected_base_url = selected_base_url or _config_value("DASHSCOPE_BASE_URL")
            selected_api_key = selected_api_key or _config_value("DASHSCOPE_API_KEY")
            selected_model = selected_model or _config_value("QWEN_TEXT_MODEL", "qwen-plus")
        elif provider == "deepseek":
            selected_base_url = selected_base_url or _config_value("DEEPSEEK_BASE_URL")
            selected_api_key = selected_api_key or _config_value("DEEPSEEK_API_KEY")
            selected_model = selected_model or _config_value("DEEPSEEK_MODEL")
        elif provider == "baichuan":
            selected_base_url = selected_base_url or _config_value("BAICHUAN_BASE_URL")
            selected_api_key = selected_api_key or _config_value("BAICHUAN_API_KEY")
            selected_model = selected_model or _config_value("BAICHUAN_TEXT_MODEL")
        else:
            selected_base_url = selected_base_url or _config_value("ARK_BASE_URL")
            selected_api_key = selected_api_key or _config_value("ARK_API_KEY")
            selected_model = selected_model or _config_value("DOUBAO_TEXT_MODEL", DEFAULT_MODEL)

    if not selected_base_url:
        raise ValueError("LLM base_url is empty; set config or pass --base-url")
    if not selected_api_key:
        raise ValueError("LLM api_key is empty; set config or pass --api-key")
    if not selected_model:
        raise ValueError("LLM model is empty; set config or pass --model")

    client = OpenAI(api_key=selected_api_key, base_url=selected_base_url, timeout=(5.0, 120.0))

    def call(prompt: str) -> str:
        response = client.chat.completions.create(
            model=selected_model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )
        return response.choices[0].message.content or "{}"

    logger.info(f"Using LLM provider={provider}, model={selected_model}")
    return call


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="调用 LLM 分析 wuweiping_template_prescription.txt 模板方。")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT_FILE, help=f"输入 txt，默认 {DEFAULT_INPUT_FILE}")
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT_FILE, help=f"输出 JSON，默认 {DEFAULT_OUTPUT_FILE}"
    )
    parser.add_argument("--chunk-size", type=int, default=20, help="每批发送给 LLM 的模板方数量，默认 20")
    parser.add_argument("--delay", type=float, default=1.0, help="批次请求间隔秒数，默认 1.0")
    parser.add_argument("--model", default=None, help="覆盖 config 中的 LLM 模型名")
    parser.add_argument("--base-url", default=None, help="覆盖 config 中的 OpenAI 兼容 base_url")
    parser.add_argument("--api-key", default=None, help="覆盖 config 中的 API key")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    llm_call = create_llm_call(model=args.model, base_url=args.base_url, api_key=args.api_key)
    result = analyze_file(args.input, args.output, llm_call, chunk_size=args.chunk_size, delay=args.delay)
    print(json.dumps(result["metadata"], ensure_ascii=False, indent=2))
    print(f"Saved to {args.output}")


if __name__ == "__main__":
    main()
